name: Terraform AWS Infracost Workflow

on:
  push:
    branches: [ main ]

jobs:
  tf_code_check:
    name: Terraform Validation and Build
    runs-on: ubuntu-latest
    env:
      TF_ROOT: terraform/create-ec2/
    defaults:
     run:
      working-directory: ${{ env.TF_ROOT }}
      
    steps:
    - uses: actions/checkout@v2.5.0  

    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1
      env:
        AWS_DEFAULT_REGION:
        AWS_REGION:
        AWS_ACCESS_KEY_ID:
        AWS_SECRET_ACCESS_KEY:
        AWS_SESSION_TOKEN:
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.2

    - name: Terraform path
      run: |
        echo `pwd`
        echo "tfpath terraform/create-ec2/"
        
    - name: Terraform fmt
      run: |
        echo "** Running Terraform fmt***"
        terraform fmt
        
        
    - name: Terraform init
      run: |
        echo "** Running Terraform init***"
        terraform init
        
        
    - name: Terraform validate
      run: |
        echo "** Running Terraform validate**"
        terraform validate
        
    - name: Terraform plan
      run: |
        echo "** Running Terraform plan***"
        terraform plan
        
    - name: Terraform apply
      run: |
        echo "** Running Terraform apply***"
        terraform apply -auto-approve
        
    - name: Terraform destroy
      run: |
        echo "** Running Terraform destroy***"
        terraform destroy -auto-approve
